### ISSUE TITLE
`claypoole/pmap` expects to be passed functions for the seq arguments 

### ISSUE THREAD

**Issue by miridius** [clj-kondo/clj-kondo.configs#5]
I'm using clj-kondo v2024.08.29. This happens in both the native and JVM versions

With empty configs apart from `io.github.clj-kondo/config-org.clj-commons-claypoole {:mvn/version "1.0.1"}`, `cp/pmap` emits a linter error when you pass a seq(able) as the coll, saying it expects functions:

```sh
❯ clj-kondo --lint - <<< '(ns foo (:require [com.climate.claypoole :as cp])) (cp/pmap 5 inc (range 10))'      
<stdin>:1:52: error: Expected: function, received: seq.
linting took 17ms, errors: 1, warnings: 0
``` 

This tests in https://github.com/clj-kondo/configs/blob/main/configs/org.clj-commons/claypoole/test/clj_kondo/claypoole_test.clj pass only because the examples use a vector for the coll, and vectors happen to be functions too

Fixing this via global config overrides doesn't seem to work. I tried: `{:lint-as {com.climate.claypoole/pmap clojure.core/do}}` and `{:linters :type-mismatch {:namespaces {com.climate.claypoole {pmap {:arities {:varargs {:args [{:op :rest :spec :any}] :ret :seq}}}}` but the error persists

**Comment by borkdude** [comment]
I’m at a conference right now but I can look afterwards

https://www.michielborkent.nl
https://www.eetvoorjeleven.nu

**Comment by borkdude** [comment]
@miridius Since you know the solution, could you make a PR that updates the test code and the configuration?

**Comment by miridius** [comment]
HI @borkdude, I had a go at it but couldn't figure out how to get this project up locally. Where I'm stuck is that I can't figure out how to run the tests. There isn't a `:test` `deps.edn` alias, there's a `bb/tasks.clj` but it's empty, and there's a test file but it's built as a main class, and running it as a main class fails due to missing dependencies. Could you give some tips and/or perhaps add a `Contributing` section to the project readme?

**Comment by borkdude** [comment]
Currently there aren't any automated tests. I'm just viewing https://github.com/clj-kondo/configs/blob/main/configs/org.clj-commons/claypoole/test/clj_kondo/claypoole_test.clj in my editor and if there doesn't appear any errors in my editor, then it's fine :)

**Comment by miridius** [comment]
Ah! ok thanks, that works :)

**Comment by miridius** [comment]
Hi @borkdude, this has been closed for a while but the config changes don't seem to have been released - when we run `--copy-configs` we still get the old config. Possibly related: https://github.com/clj-commons/claypoole/issues/65

What are the next steps here? Anything we can do to help?

**Comment by borkdude** [comment]
What do you mean, released?
